version: "2"

services:
  apache:
    # Build from Dockerfile because we want to fix TimeZone as well as have httpd.conf and index.html cooked in it.
    build: apache/
    hostname: apache
    ports:
      - "80:80"
    volumes:
      # Fix time and timezone of the container.
      - /etc/localtime:/etc/localtime

  jenkins:
    # Build the jenkins image from the jenkins/ directory.
    # We need to do it because we need to add plugins to jenkins.
    build: jenkins/
    hostname: jenkins
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - /etc/localtime:/etc/localtime
      - /opt/containers/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/lib/x86_64-linux-gnu/libapparmor.so.1.1.0:/lib/x86_64-linux-gnu/libapparmor.so.1
    command: --prefix=/jenkins

  artifactory:
    image: mattgruter/artifactory:3.9.2
    hostname: artifactory
    ## build: artifactory/
    volumes:
      - /etc/localtime:/etc/localtime
      - /artifactory/data
      - /artifactory/logs
      - /artifactory/backup
    environment:
      - JAVA_OPTS='-Djsse.enableSNIExtension=false'

  registry:
    # Note: registry needs Docker daemon to run with: "-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock --insecure-registry <REGISTRY_HOSTNAME>:5000"
    # Question: How do we know the name of REGISTRY_HOSTNAME in advance? or what value do I fill in there?
    # Build registry image from registry directory.
    # build: registry/
    image: registry:2
    hostname: registry
    ports:
      - "5000:5000"
    volumes:
      # For some strange reason Docker registry container stores the images in /tmp/registry .
      - /etc/localtime:/etc/localtime
      # Registry:2 uses /var/lib/registry for storage
      - /var/lib/registry
